#ifndef _STATES_H
#define _STATES_H

#define FLAG_DISPATCH_TYPE_OPENBK_LIGHT 1

#define FLAG_DISPATCH_ACTION_OPENBK_LIGHT_POWER_ON 1
#define FLAG_DISPATCH_ACTION_OPENBK_LIGHT_POWER_OFF 2
#define FLAG_DISPATCH_ACTION_OPENBK_LIGHT_BRIGHTNESS 3

#endif
